FROM ubuntu:18.04
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install apt-utils
RUN apt-get -y install openjdk-8-jre-headless
RUN apt-get -y install sqlite3
RUN apt-get -y install zip
RUN apt-get -y install unzip
RUN apt-get -y install wget
RUN apt-get -y install curl
RUN apt-get -y install bsdutils
RUN apt-get -y install mysql-client
RUN apt-get -y install python3
RUN apt-get -y install python
